### ISSUE TITLE
pta.transform.by_query() for transform_iter

### ISSUE THREAD

**Issue by cmacdonald** [seanmacavaney/pyterrier-alpha#5]
Implementation is straightforward. The question is more how it should be specified. Three options:

1. Specify an iter=True kwarg

2. Call decorator pta.transform_iter.by_query()

3. Decorator checks name of method: transform -> dataframe,
transform_iter -> iterdict

**Comment by seanmacavaney** [comment]
3 is really compelling. I vote we go this route. We can always revise later if there's an unexpected downside.

**Comment by cmacdonald** [comment]
Amazing, thanks

**Comment by cmacdonald** [comment]
I knew you would jump for 3
